name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
    permissions:
      contents: write
    steps:
      - uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          config_theme: dark

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_topics: yes
          plugin_habits: yes
          plugin_reactions: yes
