name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
    permissions:
      contents: write
    steps:
      - uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # theme / dark mode
          config_theme: github_dark
          config_output: svg
          # core sections (if supported)
          base: header, activity, community, repositories, metadata
          # plugins (if supported)
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_licenses: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 5594784
